export const deviceList = [
    { id: '0', name: 'Freeform', symbols: [], maxWaypointNameLength: 100 },
    {
        id: '1',
        name: 'Humminbird',
        symbols: [
            { id: 1, name: 'Waypoint', value: 0 },
            { id: 71, name: 'Bridge Icon', value: 71 },
            { id: 72, name: 'Turkey', value: 68 },
            { id: 73, name: 'Bad Ice Hole', value: 31 },
            { id: 74, name: 'MOB', value: 30 },
            { id: 75, name: 'Snapshot', value: 29 },
            { id: 76, name: 'Recording', value: 28 },
            { id: 77, name: 'Timber', value: 27 },
            { id: 78, name: 'Water', value: 26 },
            { id: 79, name: 'Shower', value: 25 },
            { id: 80, name: 'Pattern', value: 24 },
            { id: 81, name: 'Flag', value: 23 },
            { id: 82, name: 'Diamond', value: 22 },
            { id: 83, name: 'Circle', value: 21 },
            { id: 84, name: 'Boat Ramp', value: 20 },
            { id: 85, name: 'Slip', value: 19 },
            { id: 86, name: 'Pier', value: 18 },
            { id: 87, name: 'Moor', value: 17 },
            { id: 88, name: 'Beverage', value: 16 },
            { id: 89, name: 'Restaurant', value: 15 },
            { id: 90, name: 'Home', value: 1 },
            { id: 91, name: 'Cross', value: 2 },
            { id: 92, name: 'Fish', value: 3 },
            { id: 93, name: 'Duck', value: 4 },
            { id: 94, name: 'Buoy', value: 5 },
            { id: 95, name: 'Anchor', value: 6 },
            { id: 96, name: 'Bass', value: 32 },
            { id: 97, name: 'Airport', value: 7 },
            { id: 98, name: 'Danger', value: 9 },
            { id: 99, name: 'Gas', value: 10 },
            { id: 100, name: 'Rocks', value: 11 },
            { id: 101, name: 'Weed', value: 12 },
            { id: 102, name: 'Wreck', value: 13 },
            { id: 103, name: 'Phone', value: 14 },
            { id: 104, name: 'Camp', value: 8 },
            { id: 105, name: 'Beach', value: 33 },
            { id: 106, name: 'Beacon', value: 34 },
            { id: 107, name: 'Car', value: 35 },
            { id: 108, name: 'Picnic', value: 54 },
            { id: 109, name: 'Playround', value: 55 },
            { id: 110, name: 'Redfish', value: 56 },
            { id: 111, name: 'Reef Icon', value: 57 },
            { id: 112, name: 'Restricted Area', value: 58 },
            { id: 113, name: 'Rock Pile', value: 59 },
            { id: 114, name: 'Panfish', value: 53 },
            { id: 115, name: 'Sailfish', value: 60 },
            { id: 116, name: 'Sand Bar', value: 62 },
            { id: 117, name: 'Striper', value: 63 },
            { id: 118, name: 'Stump', value: 64 },
            { id: 119, name: 'Swim', value: 65 },
            { id: 120, name: 'Thin Ice', value: 66 },
            { id: 121, name: 'Trout', value: 67 },
            { id: 122, name: 'Sand', value: 61 },
            { id: 123, name: 'Water Ski', value: 69 },
            { id: 124, name: 'No Horn', value: 52 },
            { id: 125, name: 'Mud', value: 50 },
            { id: 126, name: 'Coast Guard', value: 36 },
            { id: 127, name: 'Crack In Ice', value: 37 },
            { id: 128, name: 'Dam', value: 38 },
            { id: 129, name: 'Drop Off', value: 39 },
            { id: 130, name: 'Fine Cross', value: 40 },
            { id: 131, name: 'Good Catch', value: 41 },
            { id: 132, name: 'No Anchor', value: 51 },
            { id: 133, name: 'Good Ice Hole', value: 42 },
            { id: 134, name: 'Gravel', value: 44 },
            { id: 135, name: 'Grouse', value: 45 },
            { id: 136, name: 'Ice', value: 46 },
            { id: 137, name: 'Information', value: 47 },
            { id: 138, name: 'Lobster', value: 48 },
            { id: 139, name: 'Macherel', value: 49 },
            { id: 140, name: 'Grass', value: 43 },
        ],
        maxWaypointNameLength: 0,
        waypointAllowedCharacters: null,
    },
    {
        id: '2',
        name: 'Lowrance',
        symbols: [
            { id: 141, name: 'money', value: 69 },
            { id: 2, name: 'picnictable', value: 31 },
            { id: 3, name: 'campsite', value: 30 },
            { id: 4, name: 'mountains', value: 29 },
            { id: 5, name: 'tree', value: 28 },
            { id: 6, name: 'restroom', value: 27 },
            { id: 7, name: 'man', value: 26 },
            { id: 8, name: 'usflag', value: 25 },
            { id: 9, name: 'trafficlight', value: 24 },
            { id: 10, name: 'exclamation', value: 23 },
            { id: 11, name: 'stopsign', value: 22 },
            { id: 12, name: 'exitsign', value: 21 },
            { id: 13, name: 'plane', value: 20 },
            { id: 14, name: 'phone', value: 19 },
            { id: 15, name: 'forkandspoon', value: 18 },
            { id: 16, name: 'gas', value: 17 },
            { id: 17, name: 'store', value: 16 },
            { id: 18, name: 'car', value: 15 },
            { id: 19, name: 'diamond', value: 1 },
            { id: 20, name: 'cross', value: 2 },
            { id: 21, name: 'bigfish', value: 3 },
            { id: 22, name: 'smallfish', value: 4 },
            { id: 23, name: 'schoolfish', value: 5 },
            { id: 24, name: 'longfish', value: 6 },
            { id: 25, name: 'deer', value: 32 },
            { id: 26, name: 'dropoff', value: 7 },
            { id: 27, name: 'hump', value: 9 },
            { id: 28, name: 'longgrass', value: 10 },
            { id: 29, name: 'shortgrass', value: 11 },
            { id: 30, name: 'rocks', value: 12 },
            { id: 31, name: 'l_cross', value: 13 },
            { id: 32, name: 'house', value: 14 },
            { id: 33, name: 'hole', value: 8 },
            { id: 34, name: 'deertracks', value: 33 },
            { id: 35, name: 'turkeytracks', value: 34 },
            { id: 36, name: 'treestand', value: 35 },
            { id: 37, name: 'multitreasure', value: 54 },
            { id: 38, name: 'mystery', value: 55 },
            { id: 39, name: 'treasure', value: 56 },
            { id: 40, name: 'webcam', value: 57 },
            { id: 41, name: 'sun', value: 58 },
            { id: 42, name: 'musicalnote', value: 59 },
            { id: 43, name: 'letter', value: 53 },
            { id: 44, name: 'camera', value: 60 },
            { id: 45, name: 'coffeemug', value: 62 },
            { id: 46, name: 'books', value: 63 },
            { id: 47, name: 'historicalmarker', value: 64 },
            { id: 48, name: 'tools', value: 65 },
            { id: 49, name: 'favorite', value: 66 },
            { id: 50, name: 'arena', value: 67 },
            { id: 51, name: 'star', value: 61 },
            { id: 52, name: 'circle', value: 0 },
            { id: 53, name: 'ghost', value: 52 },
            { id: 54, name: 'globallocation', value: 50 },
            { id: 55, name: 'bridge', value: 36 },
            { id: 56, name: 'skullandcrossbones', value: 37 },
            { id: 57, name: 'fish', value: 38 },
            { id: 58, name: 'twofish', value: 39 },
            { id: 59, name: 'diveflag', value: 40 },
            { id: 60, name: 'wreck', value: 41 },
            { id: 61, name: 'note', value: 51 },
            { id: 62, name: 'anchor', value: 42 },
            { id: 63, name: 'boatramp', value: 44 },
            { id: 64, name: 'flagbuoy', value: 45 },
            { id: 65, name: 'dam', value: 46 },
            { id: 66, name: 'swimmer', value: 47 },
            { id: 67, name: 'pier', value: 48 },
            { id: 68, name: 'landfeature', value: 49 },
            { id: 69, name: 'boat', value: 43 },
            { id: 70, name: 'golfcourse', value: 68 },
        ],
        maxWaypointNameLength: 0,
        waypointAllowedCharacters: null,
    },
];
